/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AdminActivityLogSchema extends BaseModel {
  static $columns = ['actionType', 'adminUserId', 'createdAt', 'id', 'resourceId', 'resourceType'] as const
  $columns = AdminActivityLogSchema.$columns
  @column()
  declare actionType: string
  @column()
  declare adminUserId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare resourceId: string | null
  @column()
  declare resourceType: string | null
}

export class AdminUserSchema extends BaseModel {
  static $columns = ['createdAt', 'createdById', 'email', 'id', 'isActive', 'passwordChanged', 'passwordHash', 'role', 'totpEnabled', 'totpSecret', 'updatedAt'] as const
  $columns = AdminUserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdById: string | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare passwordChanged: boolean
  @column()
  declare passwordHash: string
  @column()
  declare role: any
  @column()
  declare totpEnabled: boolean
  @column()
  declare totpSecret: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MemberSchema extends BaseModel {
  static $columns = ['bureauRole', 'city', 'country', 'createdAt', 'deactivatedAt', 'email', 'expertiseDomains', 'filiereEnspy', 'firstName', 'id', 'isBureauActive', 'lastName', 'latitude', 'linkedinUrl', 'longitude', 'northAmericaJob', 'northAmericaSchoolPath', 'photoUrl', 'promotionEnspy', 'slug', 'telegram', 'updatedAt'] as const
  $columns = MemberSchema.$columns
  @column()
  declare bureauRole: string | null
  @column()
  declare city: string | null
  @column()
  declare country: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deactivatedAt: DateTime | null
  @column()
  declare email: string | null
  @column()
  declare expertiseDomains: any | null
  @column()
  declare filiereEnspy: string | null
  @column()
  declare firstName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isBureauActive: boolean
  @column()
  declare lastName: string
  @column()
  declare latitude: string | null
  @column()
  declare linkedinUrl: string | null
  @column()
  declare longitude: string | null
  @column()
  declare northAmericaJob: string | null
  @column()
  declare northAmericaSchoolPath: string | null
  @column()
  declare photoUrl: string | null
  @column()
  declare promotionEnspy: string | null
  @column()
  declare slug: string
  @column()
  declare telegram: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProductionFileSchema extends BaseModel {
  static $columns = ['createdAt', 'fileKey', 'id', 'mimeType', 'originalName', 'productionId', 'sizeBytes', 'storageProvider', 'updatedAt'] as const
  $columns = ProductionFileSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fileKey: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare mimeType: string
  @column()
  declare originalName: string
  @column()
  declare productionId: string
  @column()
  declare sizeBytes: bigint | number
  @column()
  declare storageProvider: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProductionLinkSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'label', 'linkType', 'productionId', 'updatedAt', 'url'] as const
  $columns = ProductionLinkSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare label: string | null
  @column()
  declare linkType: any
  @column()
  declare productionId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare url: string
}

export class ProductionSchema extends BaseModel {
  static $columns = ['antaPublishedAt', 'authors', 'category', 'createdAt', 'createdById', 'domain', 'id', 'institution', 'isbnDoiIssn', 'journal', 'language', 'licenseStatus', 'publicationCountry', 'publisher', 'searchVector', 'status', 'subdomain', 'summary', 'tags', 'title', 'updatedAt', 'workPublishedAt'] as const
  $columns = ProductionSchema.$columns
  @column.dateTime()
  declare antaPublishedAt: DateTime | null
  @column()
  declare authors: any
  @column()
  declare category: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdById: string | null
  @column()
  declare domain: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare institution: string | null
  @column()
  declare isbnDoiIssn: string | null
  @column()
  declare journal: string | null
  @column()
  declare language: string | null
  @column()
  declare licenseStatus: any
  @column()
  declare publicationCountry: string | null
  @column()
  declare publisher: string | null
  @column()
  declare searchVector: string | null
  @column()
  declare status: any
  @column()
  declare subdomain: string | null
  @column()
  declare summary: string | null
  @column()
  declare tags: any
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.date()
  declare workPublishedAt: DateTime | null
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class StatsDownloadSchema extends BaseModel {
  static $columns = ['downloadedAt', 'id', 'ipHash', 'productionId'] as const
  $columns = StatsDownloadSchema.$columns
  @column.dateTime()
  declare downloadedAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipHash: string | null
  @column()
  declare productionId: string
}

export class StatsViewSchema extends BaseModel {
  static $columns = ['id', 'ipHash', 'productionId', 'recordedAt', 'sessionId'] as const
  $columns = StatsViewSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipHash: string | null
  @column()
  declare productionId: string
  @column.dateTime()
  declare recordedAt: DateTime
  @column()
  declare sessionId: string | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'isActive', 'password', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
