/**
 * Taxonomies prédéfinies pour les productions (clés stockées en BD, libellés i18n côté client).
 * Miroir client : `inertia/lib/taxonomy.ts` — garder synchronisés.
 */

export const PRODUCTION_CATEGORIES = [
  'book',
  'article',
  'video',
  'music',
  'podcast',
  'thesis',
  'report',
  'memoir',
  'note',
  'conference_proceedings',
  'working_paper',
] as const

export type ProductionCategory = (typeof PRODUCTION_CATEGORIES)[number]

export const PRODUCTION_DOMAINS = [
  'mathematics',
  'computer_science',
  'artificial_intelligence',
  'biology',
  'history',
  'economics',
  'linguistics',
  'physics',
  'chemistry',
  'medicine',
  'engineering',
  'philosophy',
  'psychology',
  'sociology',
  'political_science',
  'education',
  'law',
  'geography',
  'environmental_science',
  'finance',
  'literature',
] as const

export type ProductionDomain = (typeof PRODUCTION_DOMAINS)[number]

export const SUBDOMAINS_BY_DOMAIN: Record<ProductionDomain, readonly string[]> = {
  mathematics: [
    'topology',
    'algebra',
    'analysis',
    'geometry',
    'number_theory',
    'probability',
    'optimization',
    'discrete_mathematics',
    'dynamical_systems',
    'mathematical_logic',
    'numerical_analysis',
    'applied_mathematics',
  ],
  computer_science: [
    'networks',
    'algorithms',
    'software_engineering',
    'databases',
    'cryptography',
    'human_computer_interaction',
    'distributed_systems',
    'operating_systems',
    'compilers',
    'computer_vision',
    'natural_language_processing',
    'theory_of_computation',
    'cybersecurity',
    'cloud_computing',
    'data_science',
    'data_engineering',
    'data_structures',
  ],
  artificial_intelligence: [
    'machine_learning',
    'deep_learning',
    'reinforcement_learning',
    'knowledge_representation',
    'expert_systems',
    'multi_agent_systems',
    'computer_vision',
    'natural_language_processing',
    'robotics',
    'planning',
    'reasoning',
    'generative_ai',
  ],
  biology: [
    'genetics',
    'ecology',
    'microbiology',
    'zoology',
    'botany',
    'biochemistry',
    'molecular_biology',
    'cell_biology',
    'evolutionary_biology',
    'neuroscience',
    'physiology',
    'immunology',
    'bioinformatics',
  ],
  history: [
    'medieval_history',
    'ancient_history',
    'modern_history',
    'african_history',
    'social_history',
    'economic_history',
    'political_history',
    'intellectual_history',
    'cultural_history',
    'global_history',
    'history_of_science',
    'oral_history',
  ],
  economics: [
    'macroeconomics',
    'microeconomics',
    'development_economics',
    'econometrics',
    'finance',
    'labor_economics',
    'international_economics',
    'behavioral_economics',
    'public_economics',
    'industrial_organization',
    'monetary_economics',
    'game_theory',
  ],
  linguistics: [
    'phonetics',
    'sociolinguistics',
    'syntax',
    'semantics',
    'psycholinguistics',
    'historical_linguistics',
    'morphology',
    'pragmatics',
    'discourse_analysis',
    'typology',
    'computational_linguistics',
    'corpus_linguistics',
  ],
  physics: [
    'classical_mechanics',
    'quantum_mechanics',
    'thermodynamics',
    'statistical_physics',
    'electromagnetism',
    'optics',
    'astrophysics',
    'particle_physics',
    'condensed_matter',
    'relativity',
    'nuclear_physics',
    'plasma_physics',
  ],
  chemistry: [
    'organic_chemistry',
    'inorganic_chemistry',
    'physical_chemistry',
    'analytical_chemistry',
    'biochemistry',
    'materials_chemistry',
    'computational_chemistry',
    'chemical_engineering',
    'polymer_chemistry',
    'environmental_chemistry',
  ],
  medicine: [
    'internal_medicine',
    'epidemiology',
    'public_health',
    'cardiology',
    'oncology',
    'neurology',
    'psychiatry',
    'surgery',
    'radiology',
    'dermatology',
    'pharmacology',
    'clinical_research',
  ],
  engineering: [
    'mechanical_engineering',
    'electrical_engineering',
    'civil_engineering',
    'chemical_engineering',
    'industrial_engineering',
    'systems_engineering',
    'aerospace_engineering',
    'materials_engineering',
    'environmental_engineering',
    'robotics',
    'control_systems',
    'signal_processing',
  ],
  philosophy: [
    'ethics',
    'epistemology',
    'metaphysics',
    'logic',
    'philosophy_of_science',
    'political_philosophy',
    'aesthetics',
    'philosophy_of_mind',
    'social_philosophy',
    'continental_philosophy',
    'analytic_philosophy',
  ],
  psychology: [
    'cognitive_psychology',
    'developmental_psychology',
    'social_psychology',
    'clinical_psychology',
    'behavioral_psychology',
    'neuropsychology',
    'personality_psychology',
    'psychometrics',
    'educational_psychology',
    'health_psychology',
  ],
  sociology: [
    'social_theory',
    'inequality',
    'family_sociology',
    'urban_sociology',
    'economic_sociology',
    'political_sociology',
    'sociology_of_education',
    'sociology_of_work',
    'demography',
    'criminology',
    'cultural_sociology',
  ],
  political_science: [
    'comparative_politics',
    'international_relations',
    'public_policy',
    'political_theory',
    'comparative_institutions',
    'public_administration',
    'geopolitics',
    'electoral_studies',
    'conflict_studies',
    'governance',
  ],
  education: [
    'curriculum_studies',
    'instructional_design',
    'educational_technology',
    'higher_education',
    'special_education',
    'learning_sciences',
    'assessment',
    'pedagogy',
    'teacher_education',
    'educational_psychology',
  ],
  law: [
    'constitutional_law',
    'criminal_law',
    'civil_law',
    'administrative_law',
    'international_law',
    'commercial_law',
    'labor_law',
    'tax_law',
    'intellectual_property',
    'human_rights_law',
  ],
  geography: [
    'human_geography',
    'physical_geography',
    'gis',
    'cartography',
    'urban_studies',
    'regional_planning',
    'climatology',
    'geomorphology',
    'population_geography',
    'transport_geography',
  ],
  environmental_science: [
    'climate_science',
    'conservation',
    'ecology',
    'sustainability',
    'pollution',
    'natural_resource_management',
    'hydrology',
    'oceanography',
    'environmental_policy',
    'biodiversity',
  ],
  finance: [
    'asset_pricing',
    'portfolio_management',
    'risk_management',
    'derivatives',
    'corporate_finance',
    'financial_econometrics',
    'market_microstructure',
    'quantitative_finance',
    'behavioral_finance',
    'fintech',
    'cryptocurrency',
    'sustainable_finance',
  ],
  literature: [
    'comparative_literature',
    'poetry',
    'novel_studies',
    'drama',
    'narratology',
    'literary_criticism',
    'world_literature',
    'postcolonial_literature',
    'children_literature',
    'creative_writing',
  ],
}

export function isProductionCategory(value: string): value is ProductionCategory {
  return (PRODUCTION_CATEGORIES as readonly string[]).includes(value)
}

export function isProductionDomain(value: string): value is ProductionDomain {
  return (PRODUCTION_DOMAINS as readonly string[]).includes(value)
}

export function allowedSubdomainsForDomain(domain: string | null | undefined): readonly string[] {
  if (!domain || !isProductionDomain(domain)) return []
  return SUBDOMAINS_BY_DOMAIN[domain]
}

export function filterSubdomainsForDomain(
  domain: string | null | undefined,
  subdomains: string[]
): string[] {
  const allowed = new Set(allowedSubdomainsForDomain(domain))
  return subdomains.filter((s) => allowed.has(s))
}
