/**
 * Liste des pays (noms français) pour le champ « Pays de publication ».
 * Les pays africains sont regroupés en tête (UX-DR : public cible africain).
 */
export const AFRICAN_COUNTRIES: string[] = [
  'Afrique du Sud',
  'Algérie',
  'Angola',
  'Bénin',
  'Botswana',
  'Burkina Faso',
  'Burundi',
  'Cameroun',
  'Cap-Vert',
  'Comores',
  'Congo (Brazzaville)',
  'Congo (RDC)',
  "Côte d'Ivoire",
  'Djibouti',
  'Égypte',
  'Érythrée',
  'Eswatini',
  'Éthiopie',
  'Gabon',
  'Gambie',
  'Ghana',
  'Guinée',
  'Guinée-Bissau',
  'Guinée équatoriale',
  'Kenya',
  'Lesotho',
  'Libéria',
  'Libye',
  'Madagascar',
  'Malawi',
  'Mali',
  'Maroc',
  'Maurice',
  'Mauritanie',
  'Mozambique',
  'Namibie',
  'Niger',
  'Nigéria',
  'Ouganda',
  'République centrafricaine',
  'Rwanda',
  'São Tomé-et-Príncipe',
  'Sénégal',
  'Seychelles',
  'Sierra Leone',
  'Somalie',
  'Soudan',
  'Soudan du Sud',
  'Tanzanie',
  'Tchad',
  'Togo',
  'Tunisie',
  'Zambie',
  'Zimbabwe',
]

export const OTHER_COUNTRIES: string[] = [
  'Afghanistan',
  'Albanie',
  'Allemagne',
  'Andorre',
  'Antigua-et-Barbuda',
  'Arabie saoudite',
  'Argentine',
  'Arménie',
  'Australie',
  'Autriche',
  'Azerbaïdjan',
  'Bahamas',
  'Bahreïn',
  'Bangladesh',
  'Barbade',
  'Belgique',
  'Belize',
  'Bhoutan',
  'Biélorussie',
  'Birmanie (Myanmar)',
  'Bolivie',
  'Bosnie-Herzégovine',
  'Brésil',
  'Brunei',
  'Bulgarie',
  'Cambodge',
  'Canada',
  'Chili',
  'Chine',
  'Chypre',
  'Colombie',
  'Corée du Nord',
  'Corée du Sud',
  'Costa Rica',
  'Croatie',
  'Cuba',
  'Danemark',
  'Dominique',
  'Émirats arabes unis',
  'Équateur',
  'Espagne',
  'Estonie',
  'États-Unis',
  'Fidji',
  'Finlande',
  'France',
  'Géorgie',
  'Grèce',
  'Grenade',
  'Guatemala',
  'Guyana',
  'Haïti',
  'Honduras',
  'Hongrie',
  'Îles Marshall',
  'Îles Salomon',
  'Inde',
  'Indonésie',
  'Irak',
  'Iran',
  'Irlande',
  'Islande',
  'Israël',
  'Italie',
  'Jamaïque',
  'Japon',
  'Jordanie',
  'Kazakhstan',
  'Kirghizistan',
  'Kiribati',
  'Koweït',
  'Laos',
  'Lettonie',
  'Liban',
  'Liechtenstein',
  'Lituanie',
  'Luxembourg',
  'Macédoine du Nord',
  'Malaisie',
  'Maldives',
  'Malte',
  'Mexique',
  'Micronésie',
  'Moldavie',
  'Monaco',
  'Mongolie',
  'Monténégro',
  'Nauru',
  'Népal',
  'Nicaragua',
  'Norvège',
  'Nouvelle-Zélande',
  'Oman',
  'Ouzbékistan',
  'Pakistan',
  'Palaos',
  'Palestine',
  'Panama',
  'Papouasie-Nouvelle-Guinée',
  'Paraguay',
  'Pays-Bas',
  'Pérou',
  'Philippines',
  'Pologne',
  'Portugal',
  'Qatar',
  'République dominicaine',
  'République tchèque',
  'Roumanie',
  'Royaume-Uni',
  'Russie',
  'Saint-Kitts-et-Nevis',
  'Saint-Marin',
  'Saint-Vincent-et-les-Grenadines',
  'Sainte-Lucie',
  'Salvador',
  'Samoa',
  'Serbie',
  'Singapour',
  'Slovaquie',
  'Slovénie',
  'Sri Lanka',
  'Suède',
  'Suisse',
  'Suriname',
  'Syrie',
  'Tadjikistan',
  'Taïwan',
  'Thaïlande',
  'Timor oriental',
  'Tonga',
  'Trinité-et-Tobago',
  'Turkménistan',
  'Turquie',
  'Tuvalu',
  'Ukraine',
  'Uruguay',
  'Vanuatu',
  'Vatican',
  'Venezuela',
  'Viêt Nam',
  'Yémen',
]

/** Tous les pays (africains d'abord). Utile pour valider une valeur connue. */
export const ALL_COUNTRIES: string[] = [...AFRICAN_COUNTRIES, ...OTHER_COUNTRIES]
